const std = @import("std");

/// Known HTML tag names for fast comparison.
/// Used throughout the DOM and parser layers.
pub const TagName = enum {
    html,
    head,
    body,
    title,
    meta,
    link,
    style,
    script,
    div,
    span,
    p,
    a,
    img,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    ul,
    ol,
    li,
    table,
    tr,
    td,
    th,
    thead,
    tbody,
    form,
    input,
    button,
    textarea,
    select,
    option,
    br,
    hr,
    area,
    base,
    col,
    embed,
    param,
    source,
    track,
    wbr,
    nav,
    header,
    footer,
    main,
    section,
    article,
    aside,
    strong,
    em,
    code,
    pre,
    blockquote,
    unknown,

    pub fn fromString(name: []const u8) TagName {
        const map = std.StaticStringMap(TagName).initComptime(.{
            .{ "html", .html },       .{ "head", .head },             .{ "body", .body },
            .{ "title", .title },     .{ "meta", .meta },             .{ "link", .link },
            .{ "style", .style },     .{ "script", .script },         .{ "div", .div },
            .{ "span", .span },       .{ "p", .p },                   .{ "a", .a },
            .{ "img", .img },         .{ "h1", .h1 },                 .{ "h2", .h2 },
            .{ "h3", .h3 },           .{ "h4", .h4 },                 .{ "h5", .h5 },
            .{ "h6", .h6 },           .{ "ul", .ul },                 .{ "ol", .ol },
            .{ "li", .li },           .{ "table", .table },           .{ "tr", .tr },
            .{ "td", .td },           .{ "th", .th },                 .{ "thead", .thead },
            .{ "tbody", .tbody },     .{ "form", .form },             .{ "input", .input },
            .{ "button", .button },   .{ "textarea", .textarea },     .{ "select", .select },
            .{ "option", .option },   .{ "br", .br },                 .{ "hr", .hr },
            .{ "area", .area },       .{ "base", .base },             .{ "col", .col },
            .{ "embed", .embed },     .{ "param", .param },           .{ "source", .source },
            .{ "track", .track },     .{ "wbr", .wbr },               .{ "nav", .nav },
            .{ "header", .header },   .{ "footer", .footer },         .{ "main", .main },
            .{ "section", .section }, .{ "article", .article },       .{ "aside", .aside },
            .{ "strong", .strong },   .{ "em", .em },                 .{ "code", .code },
            .{ "pre", .pre },         .{ "blockquote", .blockquote },
        });
        return map.get(name) orelse .unknown;
    }

    /// Returns true for void elements that cannot have children.
    pub fn isVoid(self: TagName) bool {
        return switch (self) {
            .br, .hr, .img, .input, .meta, .link, .area, .base, .col, .embed, .param, .source, .track, .wbr => true,
            else => false,
        };
    }
};
